//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetMVC.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bakiye
    {
        public int BakiyeID { get; set; }
        public Nullable<decimal> Bakiye1 { get; set; }
        public string KullaniciADi { get; set; }
    }
}
